### ISSUE TITLE
create instance exception with data-generator

### ISSUE THREAD

**Issue by Abder88** [hobbit-project/DEBS-GC-2018#27]
Hello,
I get an error when running mvn test. bellow the logs: 

2018-04-23 15:36:04,740 DEBUG [Jena] - <Jena initialization>
2018-04-23 15:36:07,426 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing CommandQueueListener>
2018-04-23 15:36:07,427 DEBUG [org.hobbit.sdk.utils.CommandQueueListener] - <Initializing...>
2018-04-23 15:36:07,550 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 15:36:07,550 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running CommandQueueListener>
2018-04-23 15:36:07,551 DEBUG [org.hobbit.sdk.utils.CommandQueueListener] - <Initialized. Waiting for termination signal>
2018-04-23 15:36:07,581 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <CONTAINER_START signal received with imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller>
2018-04-23 15:36:07,581 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing benchmark-controller-dockerizer>
2018-04-23 15:36:07,581 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running benchmark-controller-dockerizer>
2018-04-23 15:36:07,583 DEBUG [benchmark-controller-dockerizer] - <Removing containers (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 15:36:07,690 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 15:36:07,723 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <CONTAINER_START signal received with imageName=git.project-hobbit.eu:4567/smirnp/sml-benchmark-v2/system-adapter>
2018-04-23 15:36:07,726 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing SystemAdapter>
2018-04-23 15:36:07,766 DEBUG [benchmark-controller-dockerizer] - <Creating container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 15:36:07,799 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 15:36:07,799 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 15:36:07,874 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter] - <Init finished>
2018-04-23 15:36:07,879 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter_0] - <SystemModel: {
  "@id" : "http://jenaKeyValue.com/URI",
  "queryType" : "1",
  "@context" : {
    "queryType" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    }
  }
}
>
2018-04-23 15:36:07,880 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running SystemAdapter>
2018-04-23 15:36:07,891 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <SYSTEM_READY_SIGNAL signal received>
2018-04-23 15:36:08,088 DEBUG [benchmark-controller-dockerizer] - <Starting container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller, containerId=6bd4b08447b3485a4d0bf0fb60d1db734caf5e2e7e53e5b693c8ec73ced85809)>
2018-04-23 15:36:08,528 DEBUG [benchmark-controller-dockerizer] - <Connecting container to networks (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 15:36:08,976 DEBUG [benchmark-controller-dockerizer] - <Container started (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller, containerId=6bd4b08447b3485a4d0bf0fb60d1db734caf5e2e7e53e5b693c8ec73ced85809)>
2018-04-23 15:36:08,976 DEBUG [benchmark-controller-dockerizer] - <Starting monitoring & logs reading for container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 15:36:10,255 DEBUG [benchmark-controller-dockerizer] - <2018-04-23 13:36:11,440 DEBUG [Jena] - <Jena initialization>
2018-04-23 13:36:12,109 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Init()>
2018-04-23 13:36:12,148 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <BenchmarkModel: {
  "@id" : "http://jenaKeyValue.com/experimentUri",
  "generatorLimit" : "1000",
  "generatorTimeoutMin" : "60",
  "queryType" : "1",
  "@context" : {
    "generatorLimit" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorLimit",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    },
    "generatorTimeoutMin" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorTimeoutMin",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    },
    "queryType" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    }
  }
}
>
2018-04-23 13:36:12,149 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Gen.EnvVariables: QUERY_TYPE=1, GENERATOR_LIMIT=1000, GENERATOR_TIMEOUT=60>
2018-04-23 13:36:12,149 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <createDataGenerators()>
>
## _2018-04-23 15:37:10,941 ERROR [benchmark-controller-dockerizer] - <2018-04-23 13:37:12,178 ERROR [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Got exception while trying to request the creation of an instance of the "git.project-hobbit.eu:4567/debs_2018_gc/data-generator" image.>_

java.lang.NullPointerException: Didn't got a response for a create container message.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:262)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:222)
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:235)
	at org.hobbit.core.components.AbstractBenchmarkController.createDataGenerators(AbstractBenchmarkController.java:196)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:65)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-23 13:37:12,182 ERROR [org.hobbit.core.components.AbstractBenchmarkController] - <Couldn't create generator component. Aborting.>
2018-04-23 13:37:12,182 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
java.lang.IllegalStateException: Couldn't create generator component. Aborting.
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:241)
	at org.hobbit.core.components.AbstractBenchmarkController.createDataGenerators(AbstractBenchmarkController.java:196)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:65)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-23 13:37:12,185 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <close()>
>
2018-04-23 15:37:11,986 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 15:37:11,987 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <DOCKER_CONTAINER_TERMINATED git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller received>

since i'am unable to connect : 
```
docker login git.project-hobbit.eu:4567 -u ******* -p *****
Error response from daemon: Get https://git.project-hobbit.eu:4567/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
```

It appears that the benchmarkControler is in a public repo but the Data-Generator is private (same for the eval storage).
is it possible to make them all public repositories?

**Comment by smirnp** [comment]
Hi! Please update the docker images (benchmark-controller, eval-storage) on you machine by deleting the obsolete ones via `docker rmi <imageName>` . New images will be downloaded automatically.

Data generator was removed from benchmarkController as unnecessary component.

**Comment by Abder88** [comment]
I'am using the last version, also updated the docker images but steel i'm unable to run the test, bellow the logs:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.hobbit.debs_2018_gc_samples.SampleSystemTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/kammoun/.m2/repository/org/hobbit/hobbit-java-sdk/1.1.6/hobbit-java-sdk-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/kammoun/.m2/repository/org/slf4j/slf4j-log4j12/1.7.15/slf4j-log4j12-1.7.15.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2018-04-23 20:32:22,885 DEBUG [Jena] - <Jena initialization>
2018-04-23 20:32:25,286 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing CommandQueueListener>
2018-04-23 20:32:25,286 DEBUG [org.hobbit.sdk.utils.CommandQueueListener] - <Initializing...>
2018-04-23 20:32:25,456 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 20:32:25,456 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running CommandQueueListener>
2018-04-23 20:32:25,456 DEBUG [org.hobbit.sdk.utils.CommandQueueListener] - <Initialized. Waiting for termination signal>
2018-04-23 20:32:25,477 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <CONTAINER_START signal received with imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller>
2018-04-23 20:32:25,478 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing benchmark-controller-dockerizer>
2018-04-23 20:32:25,478 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running benchmark-controller-dockerizer>
2018-04-23 20:32:25,480 DEBUG [benchmark-controller-dockerizer] - <Removing containers (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 20:32:25,574 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 20:32:25,598 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <CONTAINER_START signal received with imageName=git.project-hobbit.eu:4567/smirnp/sml-benchmark-v2/system-adapter>
2018-04-23 20:32:25,599 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Initing SystemAdapter>
2018-04-23 20:32:25,603 DEBUG [benchmark-controller-dockerizer] - <Pulling image (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 20:32:25,640 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 20:32:25,642 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 20:32:25,679 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter] - <Init finished>
2018-04-23 20:32:25,685 DEBUG [org.hobbit.debs_2018_gc_samples.System.SystemAdapter_0] - <SystemModel: {
  "@id" : "http://jenaKeyValue.com/URI",
  "queryType" : "1",
  "@context" : {
    "queryType" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    }
  }
}
>
2018-04-23 20:32:25,711 DEBUG [org.hobbit.sdk.utils.ComponentsExecutor] - <Running SystemAdapter>
2018-04-23 20:32:25,716 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <SYSTEM_READY_SIGNAL signal received>
2018-04-23 20:32:31,314 DEBUG [benchmark-controller-dockerizer] - <Creating container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 20:32:31,527 DEBUG [benchmark-controller-dockerizer] - <Starting container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller, containerId=f6ed056d8b04a025e9db7fcb2e7772fcbe4ed6e53fbb772d9ccdd2eb7e3b001f)>
2018-04-23 20:32:31,927 DEBUG [benchmark-controller-dockerizer] - <Connecting container to networks (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 20:32:32,340 DEBUG [benchmark-controller-dockerizer] - <Container started (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller, containerId=f6ed056d8b04a025e9db7fcb2e7772fcbe4ed6e53fbb772d9ccdd2eb7e3b001f)>
2018-04-23 20:32:32,340 DEBUG [benchmark-controller-dockerizer] - <Starting monitoring & logs reading for container (imageName=git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller)>
2018-04-23 20:32:33,693 DEBUG [benchmark-controller-dockerizer] - <2018-04-23 18:32:45,849 DEBUG [Jena] - <Jena initialization>
>
2018-04-23 20:32:34,729 DEBUG [benchmark-controller-dockerizer] - <2018-04-23 18:32:46,973 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Init()>
2018-04-23 18:32:47,047 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <BenchmarkModel: {
  "@id" : "http://example.com/exp1",
  "generatorLimit" : "1000",
  "generatorTimeoutMin" : "60",
  "queryType" : "1",
  "@context" : {
    "generatorLimit" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorLimit",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    },
    "generatorTimeoutMin" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/generatorTimeoutMin",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    },
    "queryType" : {
      "@id" : "http://project-hobbit.eu/sml-benchmark-v2/queryType",
      "@type" : "http://www.w3.org/2001/XMLSchema#int"
    }
  }
}
>
2018-04-23 18:32:47,048 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Gen.EnvVariables: HOBBIT_EXPERIMENT_URI=http://example.com/exp1, QUERY_TYPE=1, GENERATOR_LIMIT=1000, GENERATOR_TIMEOUT=60, HOBBIT_GENERATOR_ID=1, HOBBIT_GENERATOR_COUNT=1>
2018-04-23 18:32:47,053 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <createTaskGenerators(1)>
2018-04-23 18:32:47,059 DEBUG [org.hobbit.core.components.AbstractBenchmarkController] - <Received DATA_GENERATOR_READY_SIGNAL>
>
2018-04-23 20:33:35,310 ERROR [benchmark-controller-dockerizer] - <2018-04-23 18:33:47,081 ERROR [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Got exception while trying to request the creation of an instance of the "git.project-hobbit.eu:4567/debs_2018_gc/task-generator" image.>
java.lang.NullPointerException: Didn't got a response for a create container message.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:262)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:222)
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:235)
	at org.hobbit.core.components.AbstractBenchmarkController.createTaskGenerators(AbstractBenchmarkController.java:212)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:73)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-23 18:33:47,086 ERROR [org.hobbit.core.components.AbstractBenchmarkController] - <Couldn't create generator component. Aborting.>
2018-04-23 18:33:47,087 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
java.lang.IllegalStateException: Couldn't create generator component. Aborting.
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:241)
	at org.hobbit.core.components.AbstractBenchmarkController.createTaskGenerators(AbstractBenchmarkController.java:212)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:73)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-23 18:33:47,092 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <close()>
>
2018-04-23 20:33:36,348 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-23 20:33:36,350 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <DOCKER_CONTAINER_TERMINATED git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller received>

**Comment by smirnp** [comment]
Are you running under sudo mode? Now it looks like no container was started successfully, probably because of lack of permissions.

**Comment by Abder88** [comment]
I'm running under sudo, I think that i 'am unable to get the docker image task-generator from the git but i'am getting the benchmark-controller successfully 
```
 <Got exception while trying to request the creation of an instance of the "git.project-hobbit.eu:4567/debs_2018_gc/task-generator" image.>
java.lang.NullPointerException: Didn't got a response for a create container message.
```

**Comment by smirnp** [comment]
Could you please check using the latest code from the repository?
It seems that the code you are using not the latest one. 
I did some updates 7-10 days ago to make it interoperable with a Python implementation.

**Comment by Abder88** [comment]
**I am working as sudo with java and using the last version.** 
To avoid docker login issues, i downloaded all the required images locally, and still i got this errors ! 
>
2018-04-24 13:57:11,272 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <Gen.EnvVariables: HOBBIT_EXPERIMENT_URI=http://example.com/exp1, QUERY_TYPE=1, GENERATOR_LIMIT=1000, GENERATOR_TIMEOUT=60, HOBBIT_GENERATOR_ID=1, HOBBIT_GENERATOR_COUNT=1>
2018-04-24 13:57:11,279 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <createTaskGenerators(1)>
2018-04-24 13:57:11,281 DEBUG [org.hobbit.core.components.AbstractBenchmarkController] - <Received DATA_GENERATOR_READY_SIGNAL>
>
2018-04-24 15:57:58,678 ERROR [benchmark-controller-dockerizer] - <2018-04-24 13:58:11,296 ERROR [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Got exception while trying to request the creation of an instance of the "git.project-hobbit.eu:4567/debs_2018_gc/task-generator" image.>
java.lang.NullPointerException: Didn't got a response for a create container message.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:262)
	at org.hobbit.core.components.AbstractCommandReceivingComponent.createContainer(AbstractCommandReceivingComponent.java:222)
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:235)
	at org.hobbit.core.components.AbstractBenchmarkController.createTaskGenerators(AbstractBenchmarkController.java:212)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:73)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-24 13:58:11,298 ERROR [org.hobbit.core.components.AbstractBenchmarkController] - <Couldn't create generator component. Aborting.>
2018-04-24 13:58:11,298 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
java.lang.IllegalStateException: Couldn't create generator component. Aborting.
	at org.hobbit.core.components.AbstractBenchmarkController.createGenerator(AbstractBenchmarkController.java:241)
	at org.hobbit.core.components.AbstractBenchmarkController.createTaskGenerators(AbstractBenchmarkController.java:212)
	at org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController.init(BenchmarkController.java:73)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2018-04-24 13:58:11,301 DEBUG [org.hobbit.smlbenchmark_v2.benchmark.BenchmarkController] - <close()>
>
2018-04-24 15:57:59,743 INFO [org.hobbit.core.components.AbstractCommandReceivingComponent] - <Couldn't get the id of this Docker container. Won't be able to create containers.>
2018-04-24 15:57:59,749 DEBUG [org.hobbit.sdk.utils.commandreactions.MultipleCommandsReaction] - <DOCKER_CONTAINER_TERMINATED git.project-hobbit.eu:4567/debs_2018_gc/benchmark-controller received>

**Comment by smirnp** [comment]
Unfortunately I cannot reproduce the bug over a just cloned code. 
Which OS an JDK do you use?
If you are working in IDE, you may set breakpoints in line 68 and 79 of the MultipleCommandsReaction.class (you may jump into it from SampleSystemTestRunner.java). 
The first breakpoint (line 68) should react on any `container creation` command issued by a benchmarkController. If it reacts, then the second breakpoint (line 79) should react on `task gerenator` container creation and submit an instance of a task generator (which in included to the repository) for execution. 
Or you may share the code your are using (via github or email), I will try to check it on my machine to understand if it is a OS/Java dependent problem on not

**Comment by smirnp** [comment]
A benchmarkController itself is submitted via `createContainer` command and since it works, I may assume that the MultipleCommandsReaction.class reacts in line 68 (and it submits the benchmarkController in line 74), so the problem is not in listening commands from the commandQueue. 

Theoretically it might be, that a spawned BenchmarkController container starts to work with another commandQueue (the name is defined with use of a sessionId, which is specified as environment variable in line 61 of SampleSystemTestRunner.java). So you may check if the sessionId in the `createContainer` command (jump into it from SampleSystemTestRunner.java->CommandQueueListener.class->createCommand()->AbstractCommandReceivingComponent.java line 135) is the same as specified in line 61 of SampleSystemTestRunner.java
