### ISSUE TITLE
delivery errors

### ISSUE THREAD

**Issue by rimmmmm** [hobbit-project/DEBS-GC-2018#44]
Hi all,
I encounter this error, when running "checkHealth", 
the tests fail with and without my code 
I noticed also that docker /var/lib/docker is full

ERROR [org.hobbit.core.rabbit.DataReceiverImpl] - <Exception while waiting for delivery.>
com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.QueueingConsumer.handle(QueueingConsumer.java:203)
	at com.rabbitmq.client.QueueingConsumer.nextDelivery(QueueingConsumer.java:234)
	at org.hobbit.core.rabbit.DataReceiverImpl$MsgReceivingTask.run(DataReceiverImpl.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:554)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:509)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:503)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:62)
	at org.hobbit.core.data.RabbitQueue.close(RabbitQueue.java:90)
	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
	at org.hobbit.core.rabbit.DataReceiverImpl.close(DataReceiverImpl.java:122)
	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
	at org.hobbit.core.components.AbstractTaskGenerator.close(AbstractTaskGenerator.java:269)
	at org.hobbit.sdk.utils.ComponentsExecutor.lambda$submit$0(ComponentsExecutor.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more 
cheers

**Comment by smirnp** [comment]
Hi! Please try to check other errors above that. This error is a result of failures in other components (Probably you haven't placed dataset file into data folder or haven't modified a path to it in TaskGenerator.java)
